# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz.xci
# IP: The module: 'clk_wiz_10MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_10MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz.xci
# IP: The module: 'clk_wiz_10MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Proyecto/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_10MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
