# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/inital_values_ram2.coe}}
add_files {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/sis_completo.coe}}
add_files {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Users/Asus/Downloads/inital_values_ram2.coe}}
add_files {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Users/Asus/Downloads/PruebaTMP1.coe}}
read_verilog -library xil_defaultlib -sv {
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/TMP/ADC.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Displaypath/Displaypath.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Antirebote/Filtro_Antirebotes.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Antirebote/Filtro_boton.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/LEDs.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/TMP/MUX.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Antirebote/MUX_Filtro.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Perifericos.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Antirebote/Reset.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Selector.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Antirebote/Sincronizador.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Switches.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/TMP/TMP.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Antirebote/Top_Antirebote.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/TMP/Top_TMP.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Top_filtros/Top_filtros.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/adder.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/ALU/alu_rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/branch_unit_rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/control_unit_rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Displaypath/deco_an.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Displaypath/deco_seg.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/extend_rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/mux_2.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/mux_4.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/ALU/mux_alu_flags.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/ALU/mux_alu_result.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/pc_rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/PLL/pll.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/TMP/reg_ctrl.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/TMP/reg_datos.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/register_file_rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/ALU/restador.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/rv32i.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Displaypath/simple_counter.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Displaypath/simple_register.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/Displaypath/simple_timer.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/ALU/sumador.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/Perifericos/timer.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/RV32I/top_cpu.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/top_cpu_10MHz.sv}
  {C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/imports/Nueva carpeta/top_basys_cpu.sv}
}
read_ip -quiet {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz.xci}}
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/clk_wiz_10MHz/clk_wiz_10MHz_ooc.xdc}}]

read_ip -quiet {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc}}]

read_ip -quiet {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/data_mem/data_mem.xci}}
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc}}]

read_ip -quiet {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/instr_mem/instr_mem.xci}}
set_property used_in_implementation false [get_files -all {{c:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/sources_1/ip/instr_mem/instr_mem_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/constrs_1/imports/Nueva carpeta/Basys-3-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Taller_digitales/lab4/Funcional_control_cpu/Nueva carpeta/Nueva carpeta/project_1/project_1.srcs/constrs_1/imports/Nueva carpeta/Basys-3-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_basys_cpu -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_basys_cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_basys_cpu_utilization_synth.rpt -pb top_basys_cpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
